#ifndef FAUSTCREATOR_GLOBAL_HPP
#define FAUSTCREATOR_GLOBAL_HPP

#if defined(FAUSTCREATOR_LIBRARY)
#  define FAUSTCREATOR_EXPORT Q_DECL_EXPORT
#else
#  define FAUSTCREATOR_EXPORT Q_DECL_IMPORT
#endif

#endif
